### ISSUE TITLE
Update Readme to show how to initialise

### ISSUE THREAD

**Issue by andfinally** [venkateshwar/slim-scroll#14]
The Readme tells us to initialise the plugin using 

`new slimScroll(Element);`

But I get an error when I do this, and when I check the JS and the demo I find it's actually

`scroll.useSlimScroll()`

Can you please update the readme to show the right method?

**Comment by venkateshwar** [comment]
@andfinally It should work if you use `new slimScroll(Element)` as per the new commit. You might be using old commit code or old release.

**Comment by andfinally** [comment]
Oh right! Thanks venkateshwar!
